name: Deploy Docker

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - master
    tags:
      - v*
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - run: echo test
