name: Workflow

on:
  push:
    branches:
      - master
    # tags:
    #   - v*
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - run: echo test ${{ github.event_name }} ${{ github.ref }}
      - run: test.bash
        env:
          TRIGGER: ${{ github.event_name }}
  docker:
    needs: test
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ github.event_name }} ${{ github.ref }} ${{ startsWith(github.ref, 'refs/tags') }}

  
