name: Workflow

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo test
  docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - run: echo test32

  
