name: Workflow

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo test
  docker:
    needs: test
    if: ${{ github.event.name == 'push' }} && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ github.event.name }} ${{ github.ref }}

  
